#!/bin/bash

echo apache2 auto site installer;
echo create by zainras;
echo ==========================

echo site name ex: example.local
read sitename

echo path location ex: /var/www/exemple.local/public
read pathRoot

echo set hostname to etc/host ? [yes/no]
read isaddhost

echo create folder : $pathRoot;
mkdir -p $pathRoot;
chown -R $SUDO_USER $pathRoot;
chmod -R 755 $pathRoot;

read -r -d '' siteAvailable <<- EOM
<VirtualHost *:80>
	ServerName $sitename
	ServerAdmin webmaster@$sitename
	DocumentRoot $pathRoot
<Directory $pathRoot>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
</VirtualHost>
EOM

echo create site conf : /etc/apache2/sites-available/$sitename.conf
echo "$siteAvailable" > /etc/apache2/sites-available/$sitename.conf

echo enable site : $sitename
a2ensite $sitename.conf

echo enable mod_rewrite "a2enmod rewrite"
a2enmod rewrite

echo reload apache2 config
service apache2 reload

if [ "$isaddhost" == "yes" ]
then
	echo add hostname on etc/hosts
	echo "127.0.0.1	$sitename" >> /etc/hosts
fi